<!DOCTYPE html><html><head><meta charset="utf-8"><style>
@page{margin:34px 42px 52px}body{font-family:DejaVu Sans,sans-serif;color:#292524;font-size:11px;line-height:1.5}.header{border-bottom:3px solid #7f1d1d;padding-bottom:14px;margin-bottom:22px}.brand{color:#7f1d1d;font-size:11px;font-weight:bold;letter-spacing:1px}.title{font-size:22px;font-weight:bold;margin:4px 0}.subtitle{color:#78716c}.meta{width:100%;border-collapse:collapse;margin:16px 0 22px}.meta td{padding:7px 9px;border:1px solid #d6d3d1}.meta td:first-child{width:30%;font-weight:bold;background:#f5f5f4}.section{margin:18px 0}.section h2{font-size:13px;color:#7f1d1d;border-bottom:1px solid #fecaca;padding-bottom:5px;margin-bottom:8px}.content{white-space:pre-line}.status{display:inline-block;padding:4px 9px;background:#fef3c7;color:#92400e;font-weight:bold}.approval{margin-top:30px;width:100%;border-collapse:collapse}.approval td{width:50%;text-align:center;vertical-align:top;padding-top:8px}.signature{height:64px}.footer{position:fixed;bottom:-32px;left:0;right:0;text-align:center;color:#a8a29e;font-size:9px;border-top:1px solid #e7e5e4;padding-top:7px}
</style></head><body>
<div class="header"><div class="brand">KOPERASI SYARIAH · LAPORAN PERTANGGUNGJAWABAN</div><div class="title">{{ $laporan->judul }}</div><div class="subtitle">Dokumen dibuat otomatis oleh Sistem Informasi Koperasi</div></div>
<table class="meta"><tr><td>Periode</td><td>{{ $laporan->periode_mulai->format('d M Y') }} sampai {{ $laporan->periode_selesai->format('d M Y') }}</td></tr><tr><td>Disusun oleh</td><td>{{ $laporan->pembuat?->name ?? '-' }}</td></tr><tr><td>Tanggal pengiriman</td><td>{{ $laporan->dikirim_pada?->format('d M Y H:i') ?? 'Belum dikirim' }}</td></tr><tr><td>Status</td><td><span class="status">{{ str($laporan->status)->replace('_',' ')->upper() }}</span></td></tr></table>
@foreach(['Ringkasan'=>'ringkasan','Capaian dan Indikator'=>'capaian','Kendala'=>'kendala','Rencana Tindak Lanjut'=>'tindak_lanjut'] as $label=>$field)<div class="section"><h2>{{ $label }}</h2><div class="content">{{ $laporan->{$field} ?: '-' }}</div></div>@endforeach
<div class="section"><h2>Hasil Peninjauan Ketua</h2><div class="content">{{ $laporan->catatan_ketua ?: 'Belum ada catatan.' }}</div></div>
<table class="approval"><tr><td>Disusun oleh Pengurus,<div class="signature"></div><strong>{{ $laporan->pembuat?->name ?? '(________________)' }}</strong></td><td>Ditinjau oleh Ketua Koperasi,<div class="signature"></div><strong>{{ $laporan->peninjau?->name ?? '(________________)' }}</strong></td></tr></table>
<div class="footer">Dicetak otomatis pada {{ now()->format('d M Y H:i') }} · Dokumen ini merupakan keluaran Sistem Informasi Koperasi</div>
</body></html>
